# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "condition", # <impute.min_local>
  "Mean", # <meanVarPlot>
  "Variance", # <meanVarPlot>
  "attribute", # <normPlot>
  "value", # <normPlot>
  "Compound", # <preprocess>
  "name", # <preprocess>
  NULL
))
